import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog | create",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return <div className=''>{children}</div>;
}
